### ISSUE TITLE
[iPad] Related artists grid issues.

### ISSUE THREAD

**Issue by alloy** [artsy/emission#152]
- [x] Fix trailing artist alignment
- [x] Decide: 3 or 4 columns?
- [ ] Fix: Different column size in orientation changes

## When there’s a single trailing artist it doesn’t align to the left:

This can be seen with the artist `alex-katz`.

![simulator screen shot 02 jun 2016 14 41 50](https://cloud.githubusercontent.com/assets/2320/15745116/6d193180-28d0-11e6-81c3-7860da867516.png)

## Should have 3 columns in each orientation

According to [the design spec](https://github.com/artsy/eigen/issues/1136), it should also have 3 columns in landscape orientation. I’m not sure what @sarahscott based the 4 columns on, maybe there’s another comment elsewhere?

## When loading ‘ABOUT’ tab in landscape orientation and then changing to portrait orientation changes related artists to 2 columns.

How this should be fixed kinda depends on whether or not there are always supposed to be 3 columns. _(See above.)_

![simulator screen shot 02 jun 2016 14 50 40](https://cloud.githubusercontent.com/assets/2320/15745317/81d71096-28d1-11e6-8860-936d3c65be4b.png)

**Comment by briansw** [comment]
@mennenia adding my note from the design slack channel here:

We spec'd the ipad horizontal to display 3 per row because we thought changing the configuration between devices and orientation was difficult to manage. Since that's not the case, we'd like to display 4 per row when ipad is horizontal across all pages.
