### ISSUE TITLE
Add tap and route to other entity handling.

### ISSUE THREAD

**Issue by alloy** [artsy/emission#23]
- [x] Add a native module that can use Eigen’s `ARSwitchBoard` to open a new VC and add it to the stack. (I have a rough version [here](https://github.com/alloy/ReactNativeExperiments/blob/master/EmbedInExistingNavigationStack/EmbedInExistingNavigationStack/ARReact/ARNavigatorModule.m) which is used [here](https://github.com/alloy/ReactNativeExperiments/blob/9641d28316b879b2ce9733f74b2ac62a280ba336/EmbedInExistingNavigationStack/EmbedInExistingNavigationStack/ARReact/index.ios.js#L97-L109).)
- [x] Add tap handling to articles.
- [x] Add tap handling to artworks.
- [x] Add tap handling to shows.
- [x] Add tap handling to artists.

**Comment by orta** [comment]
[This line](https://github.com/alloy/ReactNativeExperiments/blob/master/EmbedInExistingNavigationStack/EmbedInExistingNavigationStack/ARReact/ARNavigatorModule.m#L55) - should use the `ARTopMenuVC sharedVC` `- pushViewController` to ensure UINavigation/UISplitVCs get shown as modals instead of pushes ( which will assert )

**Comment by alloy** [comment]
@sarahscott If you get to this, maybe make it so that you do the tap handling and then `console.log()` the Artsy URL that represents the tapped entity.

**Comment by alloy** [comment]
@sarahscott It seems like the `TouchableWithoutFeedback` component I used isn’t working as expected, I need to tap an area twice before it’s triggered.

**Comment by alloy** [comment]
I wonder if that issue is related to https://github.com/facebook/react-native/issues/1352
