### ISSUE TITLE
[Home] Eager clipping of rails

### ISSUE THREAD

**Issue by alloy** [artsy/emission#381]
This happens after applying the blank scroll view patch found [here](https://github.com/facebook/react-native/issues/8607#issuecomment-249530803).

![eager clipping](https://cloud.githubusercontent.com/assets/2320/19619105/e6bb8a44-985e-11e6-8658-e6de3ec46b68.gif)

**Comment by majak** [comment]
Hello @alloy , is the circle view positioned outside of its parent bounds?

**Comment by alloy** [comment]
@majak Hey, yep that’s correct. I haven’t dived into debugging it yet, but it sounds like you are already aware of that limitation? Got any tips for where to start looking?

**Comment by majak** [comment]
Ideally we don't want to traverse complete uiview hierarchy to figure out which views should be clipped and which not. So we do a small optimization: If a view should be clipped since its outside of the clipping rect we remove it without looking at its subviews.

This is pretty reasonable, but doesn't work in a case where you would have a subview of the clipped view, which is outside of the clipped view's bounds and falls into the clipping rect (so it should be visible).

IIRC this matches what we do on Android and what we are currently doing (=before the patch you've applied).

Solution here would be to modify your view hierarchy in a way that you won't have this disappearing view outside of its parent bounds. Does it sound doable?

(If this sounds like unreasonable limitation we could think about adding a way to manually prevent clipping for "special" views.)

**Comment by alloy** [comment]
> Ideally we don't want to traverse complete uiview hierarchy to figure out which views should be clipped and which not.

Aye, agreed.

> So we do a small optimization: If a view should be clipped since its outside of the clipping rect we remove it without looking at its subviews.
>
> […]
>
> IIRC this matches what we do on Android and what we are currently doing (=before the patch you've applied).

Oh indeed, I just went back to check this and I now see it, I hadn’t realised this before. There’s a 20pt difference when the view is removed _after_ applying the patch, though, so that made it more apparent, but it’s still removed too early indeed. [[Before](https://cloud.githubusercontent.com/assets/2320/19782358/d79d0348-9c8d-11e6-9769-1036327ad05c.png) | [After](https://cloud.githubusercontent.com/assets/2320/19782360/da903656-9c8d-11e6-9aa5-670488286197.png)]

> Solution here would be to modify your view hierarchy in a way that you won't have this disappearing view outside of its parent bounds. Does it sound doable?

Fair point, will take a look at that.

> If this sounds like unreasonable limitation we could think about adding a way to manually prevent clipping for "special" views.

I hear what you’re saying, but I wouldn’t be a big fan of having to somehow declare that special case. I’m wondering if most cases couldn’t be solved by:

* having about 1 page worth of content ready, i.e. not remove subviews until they are more than 1 time the content size away?
* or if the total actual bounding box of all subviews couldn’t be calculated/cached when the shadow views calculate their layouts?

**Comment by alloy** [comment]
@majak Ok, so I indeed solved out issue by reworking the hierarchy a bit to ensure the button lies within its superview’s bounds 👍 

Nonetheless, if needed, I’d like to volunteer some of my time to help you perfect this change. It’s not entirely clear to me if you’re at FB and are internally working at it there? In which case I understand the ongoing work is not done in public.

**Comment by ajwhite** [comment]
I wonder if we could traverse subviews when overflow:visible is present on the top level row component

**Comment by majak** [comment]
Hey @alloy, it's great to hear you could rework your view hierarchy!
I'm at FB :) Current state of this issue is that I'm finishing a recursive implementation.
It would be really helpful if you could try that out once I publish a new patch on the issue (should be this week). The main concern for the recursive clipping is perf. It shouldn't be bad (initial testing on our lists shows roughly 3ms of clipping work per frame instead of current 2ms on iPhone5), but it's inherently more work.

**Comment by alloy** [comment]
@majak Awesome! I’d love to test it out, let me know when it’s available and I’ll do so immediately.

**Comment by majak** [comment]
Hey @alloy, the new thing is in master now. If you are not running on master apply these three commits locally:
https://github.com/facebook/react-native/commit/47839307f3bde76020fe0e05e4d38c8d66640dd4
https://github.com/facebook/react-native/commit/625c8cb83c7be01b1d5f646b70f8fb1d4c70a45c
https://github.com/facebook/react-native/commit/d5e067f244c3be28416c5ecb183e8a2b872d4fb4

**Comment by alloy** [comment]
@majak Thanks, I skimmed the diffs and it looks great! I’ll either upgrade to latest or apply these patches next week once our current release is out.
