### ISSUE TITLE
deeplink from personalized email causes crash 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#540]
gif
https://cl.ly/3a3h2J0n2B3z

unfortunately I'm not being prompted for sending the crash report, here's what I managed to pull from my phone logs https://cl.ly/3K2I2w2O2b2m

**Comment by alloy** [comment]
Hrmm, I guess it reports the errors _without_ asking the user. That doesn’t seem right, but for now it does mean we’ve got the reports.

**Comment by alloy** [comment]
This is the crash https://sentry.io/artsynet/eigen-staging/issues/274707594/. It’s related to an artwork’s `sale_artwork` being `null`, I think. Need to find such an artwork example.

**Comment by alloy** [comment]
An example is Jeff Koons. Alas this appears to be an issue in the way the query is constructed.

[This query for the ‘selected artist’](https://github.com/artsy/emission/blob/c324dc895a613a1ac150a7b45769c445d2e546bd/src/lib/containers/works_for_you.tsx#L275-L289) (which is the one you’d click in the email) is not using the Relay query fragments of the nested components like it should, instead it fetches a bunch of data itself, which includes `is_in_auction` but _not_ the `sale_artwork`.

The inclusion of `is_in_auction` [leads to the artwork component trying to access `artwork.sale_artwork`](https://github.com/artsy/emission/blob/c324dc895a613a1ac150a7b45769c445d2e546bd/src/lib/components/artwork_grids/artwork.tsx#L61-L62), but because the WFU query does not include that in its query the code fails.
