### ISSUE TITLE
Unrecognized senders are always labeled as the gallery

### ISSUE THREAD

**Issue by joeyAghion** [artsy/emission#660]
I noticed that, upon sending a message to an existing thread from my personal email, my message was labeled as coming from "Gagosian." I believe this is because the message has `is_from_user: false` [in Metaphysics](https://github.com/artsy/metaphysics/pull/680). However, we simply don't have authoritative information about senders _unless_ the messages originated in our own [authenticated] clients. These are some scenarios where the current assumptions break down:
* if a message CCs (or BCCs) additional recipients and they reply
* if a user has their email forwarded and replies from a different email address than the one they've registered with
* if an email alias is communicated offline or stored in a marketing database, later messages may come from unrecognized senders

![simulator screen shot jul 7 2017 4 31 47 pm](https://user-images.githubusercontent.com/28120/27976575-1ea7d380-6335-11e7-8921-409c896690c2.png)

We _do_ have know user identity when messages are sent via Eigen or Volt, but not otherwise, and the current implementation risks seeming broken in the above cases. I suggest we label messages with their email "display names" (usually preceding the email address in email clients) or their emails if no display names are available. This would have labeled me "Joey Aghion" in the above example. We might treat the case where messages come from Eigen/Volt specially if we want to retain the partner labeling where possible. We could go further and treat any messages from recognized (`User`/`PartnerContact`) email addresses specially, but `From` addresses are easily spoofed so I wonder if we're opening up a security hole that way.

**Comment by mzikherman** [comment]
FWIW, I do think it's nice to see 'Gagosian' instead of an individual's name (where possible/correct), but as pointed out, there are lots of common occurrences where that might not be correct, and in fact, some of those cases will always remain impossible.

My personal sentiment for now would be to thus probably drop the partner label, and just use the actual names from a per-message basis (the display name of their email address, or just their address as a fallback- typical of most mail clients).

**Comment by alloy** [comment]
@katarinabatina Can you have a think about this?

**Comment by alloy** [comment]
Fixed in https://github.com/artsy/emission/pull/696
